apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-sample
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/sample-image@sha256:8bdb0a1af9b780b6fb9b3b705fc5f3a18ac5c3b87affd1a1bf17ba922d1499b5
        name: jvm-build-test-project
        resources: {}
status: {}
